version: "3.8"

services:
    django:
        build: .
        container_name: django2
        command: python3 manage.py runserver 0.0.0.0:80
        volumes:
            - .:/usr/src/app
        ports:
            - "80:80"
        depends_on:
            - pgdb
        
    pgdb:
        image: postgres
        container_name: pgdb2
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres